-- Minimal production-shaped schema for coach_messages RLS tests.
-- Mirrors the table after 20260904060000 + 20260904071500, before hide.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  name text,
  role text not null default 'client',
  status text not null default 'pending'
);

alter table public.profiles enable row level security;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and role = 'admin'
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;

drop policy if exists "profiles_select_own_or_admin" on public.profiles;
create policy "profiles_select_own_or_admin"
  on public.profiles for select
  to authenticated
  using (id = auth.uid() or public.is_admin());

grant select on public.profiles to authenticated;

create table if not exists public.coach_messages (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null references public.profiles (id) on delete cascade,
  role text not null check (role in ('mama', 'coach')),
  body text not null default '',
  kind text not null default 'text'
    check (kind in ('text', 'cards', 'deflect', 'photo', 'read')),
  payload jsonb,
  local_date date,
  created_at timestamptz not null default now(),
  seq bigint generated by default as identity
);

alter table public.coach_messages enable row level security;

drop policy if exists "coach_messages_select_own_or_admin" on public.coach_messages;
create policy "coach_messages_select_own_or_admin"
  on public.coach_messages for select
  to authenticated
  using (profile_id = auth.uid() or public.is_admin());

drop policy if exists "coach_messages_insert_own" on public.coach_messages;
create policy "coach_messages_insert_own"
  on public.coach_messages for insert
  to authenticated
  with check (profile_id = auth.uid());

drop policy if exists "coach_messages_delete_own" on public.coach_messages;
create policy "coach_messages_delete_own"
  on public.coach_messages for delete
  to authenticated
  using (profile_id = auth.uid());

grant select, insert, update, delete on table public.coach_messages to authenticated;
grant select, insert, update, delete on table public.coach_messages to anon;
