/**
 * Macro-Friendly Brands & Pantry Staples — from Callie’s cheat sheet.
 * Individual line items for one-tap logging / planner picks (not full recipes).
 * Values are per-serving estimates (manufacturer + USDA); may vary by flavor/lot.
 */

export const PANTRY_GROUPS = [
  { id: "bars", label: "Bars & shakes" },
  { id: "dairy", label: "Dairy & yogurt" },
  { id: "bread", label: "Bread & grains" },
  { id: "snacks", label: "Packaged snacks" },
  { id: "protein", label: "Protein staples" },
  { id: "fruit", label: "Fruit" },
  { id: "fats", label: "Fats & sweeteners" },
];

/** @type {Array<{ cat: string, group: string, name: string, desc: string, cal: number, p: number, c: number, f: number, serves: number }>} */
export const PANTRY_ITEMS = [
  // —— Protein bars & shakes ——
  {
    cat: "Pantry",
    group: "bars",
    name: "Papa Steve’s No Junk Bar (Blueberry Almond)",
    desc: "1 bar (2.5 oz).",
    cal: 260,
    p: 20,
    c: 32,
    f: 10,
    serves: 1,
  },
  {
    cat: "Pantry",
    group: "bars",
    name: "Equip Prime Protein (beef isolate)",
    desc: "1 scoop (~30g).",
    cal: 100,
    p: 21,
    c: 2,
    f: 0.5,
    serves: 1,
  },
  {
    cat: "Pantry",
    group: "bars",
    name: "Lineage Animal-Based Complete",
    desc: "1 scoop (27g).",
    cal: 110,
    p: 20,
    c: 5,
    f: 1,
    serves: 1,
  },

  // —— Dairy & yogurt ——
  {
    cat: "Pantry",
    group: "dairy",
    name: "Good Culture Organic 4% Cottage Cheese",
    desc: "½ cup.",
    cal: 110,
    p: 14,
    c: 3,
    f: 4.5,
    serves: 1,
  },
  {
    cat: "Pantry",
    group: "dairy",
    name: "Kalona SuperNatural Whole Milk (4 oz)",
    desc: "4 oz.",
    cal: 75,
    p: 4,
    c: 6,
    f: 4,
    serves: 1,
  },
  {
    cat: "Pantry",
    group: "dairy",
    name: "Kalona SuperNatural Whole Milk (6 oz)",
    desc: "6 oz.",
    cal: 115,
    p: 6,
    c: 9,
    f: 6,
    serves: 1,
  },
  {
    cat: "Pantry",
    group: "dairy",
    name: "Kalona SuperNatural Whole Milk (8 oz)",
    desc: "8 oz (1 cup).",
    cal: 150,
    p: 8,
    c: 12,
    f: 8,
    serves: 1,
  },
  {
    cat: "Pantry",
    group: "dairy",
    name: "Straus Nonfat Plain Yogurt",
    desc: "1 cup European-style nonfat plain.",
    cal: 100,
    p: 8,
    c: 17,
    f: 0,
    serves: 1,
  },
  {
    cat: "Pantry",
    group: "dairy",
    name: "Straus Nonfat Greek Yogurt",
    desc: "6 oz.",
    cal: 130,
    p: 14,
    c: 17,
    f: 0,
    serves: 1,
  },
  {
    cat: "Pantry",
    group: "dairy",
    name: "Painterland Sisters Skyr, Plain",
    desc: "¾ cup.",
    cal: 160,
    p: 21,
    c: 3,
    f: 10,
    serves: 1,
  },
  {
    cat: "Pantry",
    group: "dairy",
    name: "Painterland Sisters Skyr, Strawberry",
    desc: "5.3 oz cup.",
    cal: 150,
    p: 19,
    c: 9,
    f: 8,
    serves: 1,
  },
  {
    cat: "Pantry",
    group: "dairy",
    name: "Painterland Sisters Skyr, Vanilla Bean",
    desc: "¾ cup.",
    cal: 180,
    p: 19,
    c: 12,
    f: 9,
    serves: 1,
  },
  {
    cat: "Pantry",
    group: "dairy",
    name: "Painterland Sisters Skyr, Meadow Berry",
    desc: "5.3 oz cup.",
    cal: 140,
    p: 18,
    c: 3,
    f: 9,
    serves: 1,
  },
  {
    cat: "Pantry",
    group: "dairy",
    name: "Meadow Valley Mozzarella String Cheese",
    desc: "1 stick.",
    cal: 80,
    p: 7,
    c: 1,
    f: 6,
    serves: 1,
  },
  {
    cat: "Pantry",
    group: "dairy",
    name: "Parmesan, grated",
    desc: "¼ cup.",
    cal: 110,
    p: 10,
    c: 1,
    f: 7,
    serves: 1,
  },
  {
    cat: "Pantry",
    group: "dairy",
    name: "Cheddar, shredded",
    desc: "¼ cup.",
    cal: 110,
    p: 7,
    c: 0.5,
    f: 9,
    serves: 1,
  },
  {
    cat: "Pantry",
    group: "dairy",
    name: "Cream cheese",
    desc: "¼ cup.",
    cal: 200,
    p: 4,
    c: 3,
    f: 20,
    serves: 1,
  },

  // —— Bread, wraps & grains ——
  {
    cat: "Pantry",
    group: "bread",
    name: "Sourdough bread",
    desc: "1 slice (plain, no brand).",
    cal: 120,
    p: 4,
    c: 23,
    f: 0.5,
    serves: 1,
  },
  {
    cat: "Pantry",
    group: "bread",
    name: "La Tortilla Factory Whole Wheat Tortilla",
    desc: "1 tortilla.",
    cal: 100,
    p: 4,
    c: 15,
    f: 3,
    serves: 1,
  },
  {
    cat: "Pantry",
    group: "bread",
    name: "La Tortilla Factory Original Flour Tortilla",
    desc: "1 tortilla (43g).",
    cal: 130,
    p: 3,
    c: 22,
    f: 2.5,
    serves: 1,
  },
  {
    cat: "Pantry",
    group: "bread",
    name: "Plain bagel (large)",
    desc: "1 whole large bagel.",
    cal: 280,
    p: 11,
    c: 55,
    f: 1.5,
    serves: 1,
  },
  {
    cat: "Pantry",
    group: "bread",
    name: "White rice, cooked",
    desc: "1 cup.",
    cal: 205,
    p: 4,
    c: 45,
    f: 0.5,
    serves: 1,
  },

  // —— Packaged snacks ——
  {
    cat: "Pantry",
    group: "snacks",
    name: "Dang Thai Rice Chips",
    desc: "25 chips (~1 oz).",
    cal: 150,
    p: 1,
    c: 19,
    f: 7,
    serves: 1,
  },
  {
    cat: "Pantry",
    group: "snacks",
    name: "Solely Dried Fruit Strips (mango)",
    desc: "4 pieces.",
    cal: 130,
    p: 1,
    c: 32,
    f: 0,
    serves: 1,
  },
  {
    cat: "Pantry",
    group: "snacks",
    name: "Lesser Evil Popcorn (coconut oil)",
    desc: "1 serving (~3 cups).",
    cal: 110,
    p: 2,
    c: 15,
    f: 5,
    serves: 1,
  },
  {
    cat: "Pantry",
    group: "snacks",
    name: "Firehook Baked Crackers, Sea Salt",
    desc: "7 crackers.",
    cal: 100,
    p: 3,
    c: 19,
    f: 0.5,
    serves: 1,
  },
  {
    cat: "Pantry",
    group: "snacks",
    name: "Oat Haus Granola Butter, Cookie Dough",
    desc: "2 tbsp.",
    cal: 170,
    p: 2,
    c: 15,
    f: 12,
    serves: 1,
  },
  {
    cat: "Pantry",
    group: "snacks",
    name: "Oat Haus Granola Butter, Cinnamon",
    desc: "2 tbsp.",
    cal: 170,
    p: 2,
    c: 15,
    f: 12,
    serves: 1,
  },

  // —— Protein & pantry staples ——
  {
    cat: "Pantry",
    group: "protein",
    name: "Amylu Harvest Apple Chicken Sausage",
    desc: "2 links (56g).",
    cal: 110,
    p: 10,
    c: 7,
    f: 3.5,
    serves: 1,
  },
  {
    cat: "Pantry",
    group: "protein",
    name: "Bilinski’s Mild Italian Chicken Sausage",
    desc: "1 link (68g).",
    cal: 100,
    p: 14,
    c: 1,
    f: 4.5,
    serves: 1,
  },
  {
    cat: "Pantry",
    group: "protein",
    name: "Diestel Uncured Turkey Bacon",
    desc: "2 slices (2 oz).",
    cal: 70,
    p: 10,
    c: 0,
    f: 3.5,
    serves: 1,
  },
  {
    cat: "Pantry",
    group: "protein",
    name: "Chicken breast, cooked, skinless",
    desc: "6 oz.",
    cal: 280,
    p: 53,
    c: 0,
    f: 6,
    serves: 1,
  },
  {
    cat: "Pantry",
    group: "protein",
    name: "Ground turkey (93/7), cooked",
    desc: "4 oz cooked.",
    cal: 170,
    p: 23,
    c: 0,
    f: 8,
    serves: 1,
  },
  {
    cat: "Pantry",
    group: "protein",
    name: "Ground beef (90/10), cooked",
    desc: "4 oz cooked.",
    cal: 200,
    p: 24,
    c: 0,
    f: 11,
    serves: 1,
  },
  {
    cat: "Pantry",
    group: "protein",
    name: "Hamburger patty (80/20)",
    desc: "4 oz raw / ~4.5 oz cooked.",
    cal: 285,
    p: 19,
    c: 0,
    f: 23,
    serves: 1,
  },
  {
    cat: "Pantry",
    group: "protein",
    name: "Bavette (flank) steak, cooked",
    desc: "4 oz cooked.",
    cal: 220,
    p: 28,
    c: 0,
    f: 11,
    serves: 1,
  },
  {
    cat: "Pantry",
    group: "protein",
    name: "Turkey deli slices",
    desc: "3 oz (no brand).",
    cal: 90,
    p: 18,
    c: 1,
    f: 1,
    serves: 1,
  },
  {
    cat: "Pantry",
    group: "protein",
    name: "Eggs",
    desc: "2 large.",
    cal: 140,
    p: 12,
    c: 1,
    f: 10,
    serves: 1,
  },
  {
    cat: "Pantry",
    group: "protein",
    name: "Canned tuna in water, drained",
    desc: "1 can (5 oz drained).",
    cal: 120,
    p: 27,
    c: 0,
    f: 1,
    serves: 1,
  },
  {
    cat: "Pantry",
    group: "protein",
    name: "Bone broth",
    desc: "1 cup.",
    cal: 40,
    p: 9,
    c: 0,
    f: 0,
    serves: 1,
  },

  // —— Fruit ——
  {
    cat: "Pantry",
    group: "fruit",
    name: "Peach",
    desc: "1 medium.",
    cal: 60,
    p: 1,
    c: 14,
    f: 0,
    serves: 1,
  },
  {
    cat: "Pantry",
    group: "fruit",
    name: "Nectarine",
    desc: "1 medium.",
    cal: 60,
    p: 1,
    c: 15,
    f: 0,
    serves: 1,
  },
  {
    cat: "Pantry",
    group: "fruit",
    name: "Apple",
    desc: "1 medium.",
    cal: 95,
    p: 0,
    c: 25,
    f: 0,
    serves: 1,
  },
  {
    cat: "Pantry",
    group: "fruit",
    name: "Melon (cantaloupe), cubed",
    desc: "1 cup.",
    cal: 55,
    p: 1,
    c: 13,
    f: 0,
    serves: 1,
  },
  {
    cat: "Pantry",
    group: "fruit",
    name: "Orange",
    desc: "1 medium.",
    cal: 70,
    p: 1,
    c: 16,
    f: 0,
    serves: 1,
  },
  {
    cat: "Pantry",
    group: "fruit",
    name: "Mandarin / clementine",
    desc: "1 whole.",
    cal: 35,
    p: 1,
    c: 9,
    f: 0,
    serves: 1,
  },
  {
    cat: "Pantry",
    group: "fruit",
    name: "Banana",
    desc: "1 medium.",
    cal: 105,
    p: 1,
    c: 27,
    f: 0,
    serves: 1,
  },

  // —— Fats & sweeteners ——
  {
    cat: "Pantry",
    group: "fats",
    name: "Honey",
    desc: "1 tsp.",
    cal: 21,
    p: 0,
    c: 6,
    f: 0,
    serves: 1,
  },
  {
    cat: "Pantry",
    group: "fats",
    name: "Maple syrup",
    desc: "1 tsp.",
    cal: 17,
    p: 0,
    c: 4.5,
    f: 0,
    serves: 1,
  },
  {
    cat: "Pantry",
    group: "fats",
    name: "Almond butter",
    desc: "1 tbsp.",
    cal: 98,
    p: 3.5,
    c: 3,
    f: 9,
    serves: 1,
  },
  {
    cat: "Pantry",
    group: "fats",
    name: "Peanut butter",
    desc: "1 tbsp.",
    cal: 95,
    p: 4,
    c: 3,
    f: 8,
    serves: 1,
  },
];

export function pantryByGroup(groupId) {
  if (!groupId || groupId === "all") return PANTRY_ITEMS;
  return PANTRY_ITEMS.filter((item) => item.group === groupId);
}

export function pantryGroupLabel(groupId) {
  return PANTRY_GROUPS.find((g) => g.id === groupId)?.label || groupId;
}
