-- ==================================================================
-- 20260904071500_coach_messages_seq.sql
-- Put the coach thread back in the order she read it.
-- ==================================================================

-- Her question and the answer to it are written in the same tick, so their
-- `created_at` can tie or invert and the thread came back on reload with the
-- answer above the question. An identity column records the order the rows
-- actually arrived, which is the order she saw them.
alter table public.coach_messages
  add column if not exists seq bigint generated by default as identity;

comment on column public.coach_messages.seq is
  'Arrival order. Sorted on instead of created_at, which ties between two '
  'messages written in the same tick.';

create index if not exists coach_messages_profile_seq_idx
  on public.coach_messages (profile_id, seq desc);
